name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"     # diário
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: DeividManfre
          template: classic
          base: header, activity, repositories

          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          output_action: commit
          committer_branch: output
          filename: metrics.svg
