name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # 1x/dia; pode trocar p/ semanal
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: DeividManfre
          template: classic
          base: header, activity, repositories
          config_timezone: America/Sao_Paulo

          # Módulos enxutos e profissionais
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: no

          plugin_followup: yes
          plugin_followup_sections: repositories

          output_action: commit
          committer_branch: output
          filename: metrics.svg
