name: Generate Profile Assets

on:
  schedule:
    - cron: "0 */12 * * *"   # 2x por dia, minuto 0
  workflow_dispatch:

permissions:
  contents: write            # mínimo necessário p/ publicar na branch output

concurrency:
  group: snake
  cancel-in-progress: true   # evita corrida em execuções sobrepostas

jobs:
  build:
    name: Update snake SVG
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'DeividManfre' }}  # não roda em forks

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate snake SVG
        # Versão tagueada p/ evitar supply-chain (v3.x é a major estável)
        uses: Platane/snk@v3
        with:
          github_user_name: DeividManfre
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        # Use a versão atual do action
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
